-- Flyway V1: Twitter Clone Complete Schema Down Migration

DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS tweet_hashtags CASCADE;
DROP TABLE IF EXISTS hashtags CASCADE;
DROP TABLE IF EXISTS tweet_likes CASCADE;
DROP TABLE IF EXISTS follows CASCADE;
DROP TABLE IF EXISTS tweets CASCADE;
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP EXTENSION IF EXISTS pg_trgm;
