// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embedding.sql

package db

import (
	"context"

	"github.com/pgvector/pgvector-go"
)

const listRelatedTweetsByEmbedding = `-- name: ListRelatedTweetsByEmbedding :many
SELECT tweet_id, content
FROM tweet_embeddings
ORDER BY embedding <-> $1::vector ASC
LIMIT $2
`

type ListRelatedTweetsByEmbeddingParams struct {
	Column1 *pgvector.Vector `json:"column_1"`
	Limit   int32            `json:"limit"`
}

type ListRelatedTweetsByEmbeddingRow struct {
	TweetID int64  `json:"tweet_id"`
	Content string `json:"content"`
}

func (q *Queries) ListRelatedTweetsByEmbedding(ctx context.Context, arg ListRelatedTweetsByEmbeddingParams) ([]ListRelatedTweetsByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, listRelatedTweetsByEmbedding, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelatedTweetsByEmbeddingRow{}
	for rows.Next() {
		var i ListRelatedTweetsByEmbeddingRow
		if err := rows.Scan(&i.TweetID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
