// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: follow.sql

package db

import (
	"context"
)

const followUser = `-- name: FollowUser :one
WITH inserted AS (
  INSERT INTO follows (follower_id, following_id)
  VALUES ($1, $2)
  ON CONFLICT DO NOTHING
  RETURNING follower_id, following_id
),
update_target AS (
  UPDATE users
  SET followers_count = followers_count + 1
  WHERE id = $2 AND EXISTS (SELECT 1 FROM inserted)
),
update_actor AS (
  UPDATE users
  SET following_count = following_count + 1
  WHERE id = $1 AND EXISTS (SELECT 1 FROM inserted)
)
SELECT EXISTS(SELECT 1 FROM inserted)
`

type FollowUserParams struct {
	FollowerID  int64 `json:"follower_id"`
	FollowingID int64 `json:"following_id"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, followUser, arg.FollowerID, arg.FollowingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unfollowUser = `-- name: UnfollowUser :one
WITH deleted AS (
  DELETE FROM follows
  WHERE follower_id = $1 AND following_id = $2
  RETURNING follower_id, following_id
),
update_target AS (
  UPDATE users
  SET followers_count = GREATEST(0, followers_count - 1)
  WHERE id = $2 AND EXISTS (SELECT 1 FROM deleted)
),
update_actor AS (
  UPDATE users
  SET following_count = GREATEST(0, following_count - 1)
  WHERE id = $1 AND EXISTS (SELECT 1 FROM deleted)
)
SELECT EXISTS(SELECT 1 FROM deleted)
`

type UnfollowUserParams struct {
	FollowerID  int64 `json:"follower_id"`
	FollowingID int64 `json:"following_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, unfollowUser, arg.FollowerID, arg.FollowingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
