// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hashtag.sql

package db

import (
	"context"
	"database/sql"
)

const getTopHashtagsAllTime = `-- name: GetTopHashtagsAllTime :many
SELECT id, text, usage_count, last_used_at, created_at FROM hashtags
ORDER BY usage_count DESC, last_used_at DESC
LIMIT $1
`

func (q *Queries) GetTopHashtagsAllTime(ctx context.Context, limit int32) ([]Hashtag, error) {
	rows, err := q.db.QueryContext(ctx, getTopHashtagsAllTime, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hashtag{}
	for rows.Next() {
		var i Hashtag
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.UsageCount,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrendingHashtagsLast24h = `-- name: GetTrendingHashtagsLast24h :many
SELECT h.id, h.text, h.usage_count, h.last_used_at, h.created_at
FROM hashtags h
JOIN tweet_hashtags th ON th.hashtag_id = h.id
JOIN tweets t ON t.id = th.tweet_id
WHERE t.created_at >= NOW() - INTERVAL '24 hours'
GROUP BY h.id
ORDER BY COUNT(th.tweet_id) DESC, MAX(t.created_at) DESC
LIMIT $1
`

func (q *Queries) GetTrendingHashtagsLast24h(ctx context.Context, limit int32) ([]Hashtag, error) {
	rows, err := q.db.QueryContext(ctx, getTrendingHashtagsLast24h, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hashtag{}
	for rows.Next() {
		var i Hashtag
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.UsageCount,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkTweetHashtag = `-- name: LinkTweetHashtag :exec
INSERT INTO tweet_hashtags (tweet_id, hashtag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkTweetHashtagParams struct {
	TweetID   int64 `json:"tweet_id"`
	HashtagID int64 `json:"hashtag_id"`
}

func (q *Queries) LinkTweetHashtag(ctx context.Context, arg LinkTweetHashtagParams) error {
	_, err := q.db.ExecContext(ctx, linkTweetHashtag, arg.TweetID, arg.HashtagID)
	return err
}

const searchHashtagsByPrefix = `-- name: SearchHashtagsByPrefix :many
SELECT id, text, usage_count, last_used_at, created_at FROM hashtags
WHERE LOWER(text) LIKE LOWER($1 || '%')
ORDER BY usage_count DESC
LIMIT $2
`

type SearchHashtagsByPrefixParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
}

func (q *Queries) SearchHashtagsByPrefix(ctx context.Context, arg SearchHashtagsByPrefixParams) ([]Hashtag, error) {
	rows, err := q.db.QueryContext(ctx, searchHashtagsByPrefix, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hashtag{}
	for rows.Next() {
		var i Hashtag
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.UsageCount,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHashtag = `-- name: UpsertHashtag :one
INSERT INTO hashtags (text, usage_count, last_used_at)
VALUES ($1, 1, CURRENT_TIMESTAMP)
ON CONFLICT (text) DO UPDATE
SET usage_count = hashtags.usage_count + 1,
    last_used_at = CURRENT_TIMESTAMP
RETURNING id, text, usage_count, last_used_at, created_at
`

func (q *Queries) UpsertHashtag(ctx context.Context, text string) (Hashtag, error) {
	row := q.db.QueryRowContext(ctx, upsertHashtag, text)
	var i Hashtag
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.UsageCount,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}
