// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: like.sql

package db

import (
	"context"
)

const isTweetLiked = `-- name: IsTweetLiked :one
SELECT EXISTS(
  SELECT 1
  FROM tweet_likes
  WHERE user_id = $1 AND tweet_id = $2
)
`

type IsTweetLikedParams struct {
	UserID  int64 `json:"user_id"`
	TweetID int64 `json:"tweet_id"`
}

func (q *Queries) IsTweetLiked(ctx context.Context, arg IsTweetLikedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTweetLiked, arg.UserID, arg.TweetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const likeTweet = `-- name: LikeTweet :one
WITH inserted AS (
  INSERT INTO tweet_likes (user_id, tweet_id)
  VALUES ($1, $2)
  ON CONFLICT DO NOTHING
  RETURNING user_id, tweet_id
),
updated AS (
  UPDATE tweets
  SET like_count = like_count + 1
  WHERE id = $2 AND EXISTS (SELECT 1 FROM inserted)
)
SELECT EXISTS(SELECT 1 FROM inserted)
`

type LikeTweetParams struct {
	UserID  int64 `json:"user_id"`
	TweetID int64 `json:"tweet_id"`
}

func (q *Queries) LikeTweet(ctx context.Context, arg LikeTweetParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, likeTweet, arg.UserID, arg.TweetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unlikeTweet = `-- name: UnlikeTweet :one
WITH deleted AS (
DELETE FROM tweet_likes
WHERE tweet_likes.user_id = $1 AND tweet_likes.tweet_id = $2
RETURNING user_id, tweet_id
),
updated AS (
  UPDATE tweets
  SET like_count = GREATEST(0, like_count - 1)
  WHERE id = $2 AND EXISTS (SELECT 1 FROM deleted)
)
SELECT EXISTS(SELECT 1 FROM deleted)
`

type UnlikeTweetParams struct {
	UserID  int64 `json:"user_id"`
	TweetID int64 `json:"tweet_id"`
}

func (q *Queries) UnlikeTweet(ctx context.Context, arg UnlikeTweetParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, unlikeTweet, arg.UserID, arg.TweetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
