// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package db

import (
	"context"
	"time"
)

const addConversationParticipant = `-- name: AddConversationParticipant :exec
INSERT INTO conversation_participants (conversation_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddConversationParticipantParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) AddConversationParticipant(ctx context.Context, arg AddConversationParticipantParams) error {
	_, err := q.db.Exec(ctx, addConversationParticipant, arg.ConversationID, arg.UserID)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations DEFAULT VALUES
RETURNING id, created_at, updated_at
`

func (q *Queries) CreateConversation(ctx context.Context) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation)
	var i Conversation
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const createDirectMessage = `-- name: CreateDirectMessage :one
INSERT INTO direct_messages (conversation_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, sender_id, content, created_at
`

type CreateDirectMessageParams struct {
	ConversationID int64  `json:"conversation_id"`
	SenderID       int64  `json:"sender_id"`
	Content        string `json:"content"`
}

func (q *Queries) CreateDirectMessage(ctx context.Context, arg CreateDirectMessageParams) (DirectMessage, error) {
	row := q.db.QueryRow(ctx, createDirectMessage, arg.ConversationID, arg.SenderID, arg.Content)
	var i DirectMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const findDirectConversation = `-- name: FindDirectConversation :one
SELECT c.id, c.created_at, c.updated_at
FROM conversations c
JOIN conversation_participants p1 ON p1.conversation_id = c.id AND p1.user_id = $1
JOIN conversation_participants p2 ON p2.conversation_id = c.id AND p2.user_id = $2
WHERE (SELECT COUNT(*) FROM conversation_participants cp WHERE cp.conversation_id = c.id) = 2
LIMIT 1
`

type FindDirectConversationParams struct {
	UserID   int64 `json:"user_id"`
	UserID_2 int64 `json:"user_id_2"`
}

func (q *Queries) FindDirectConversation(ctx context.Context, arg FindDirectConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, findDirectConversation, arg.UserID, arg.UserID_2)
	var i Conversation
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const isConversationParticipant = `-- name: IsConversationParticipant :one
SELECT EXISTS(
  SELECT 1
  FROM conversation_participants
  WHERE conversation_id = $1 AND user_id = $2
)
`

type IsConversationParticipantParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) IsConversationParticipant(ctx context.Context, arg IsConversationParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isConversationParticipant, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listConversationMessages = `-- name: ListConversationMessages :many
SELECT id, conversation_id, sender_id, content, created_at
FROM direct_messages
WHERE conversation_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListConversationMessagesParams struct {
	ConversationID int64 `json:"conversation_id"`
	Limit          int32 `json:"limit"`
	Offset         int32 `json:"offset"`
}

func (q *Queries) ListConversationMessages(ctx context.Context, arg ListConversationMessagesParams) ([]DirectMessage, error) {
	rows, err := q.db.Query(ctx, listConversationMessages, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DirectMessage{}
	for rows.Next() {
		var i DirectMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationParticipantIDs = `-- name: ListConversationParticipantIDs :many
SELECT user_id
FROM conversation_participants
WHERE conversation_id = $1
ORDER BY user_id ASC
`

func (q *Queries) ListConversationParticipantIDs(ctx context.Context, conversationID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listConversationParticipantIDs, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserConversations = `-- name: ListUserConversations :many
SELECT
  c.id AS conversation_id,
  c.updated_at AS conversation_updated_at,
  u.id, u.username, u.email, u.display_name, u.bio, u.avatar_url, u.role, u.provider, u.followers_count, u.following_count, u.created_at, u.updated_at,
  lm.id AS last_message_id,
  lm.sender_id AS last_sender_id,
  lm.content AS last_message_content,
  lm.created_at AS last_message_created_at
FROM conversation_participants self
JOIN conversations c ON c.id = self.conversation_id
JOIN conversation_participants otherp ON otherp.conversation_id = c.id AND otherp.user_id <> $1
JOIN users u ON u.id = otherp.user_id
JOIN LATERAL (
  SELECT dm.id, dm.sender_id, dm.content, dm.created_at
  FROM direct_messages dm
  WHERE dm.conversation_id = c.id
  ORDER BY dm.created_at DESC, dm.id DESC
  LIMIT 1
) lm ON true
WHERE self.user_id = $1
ORDER BY lm.created_at DESC, c.id DESC
LIMIT $2 OFFSET $3
`

type ListUserConversationsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUserConversationsRow struct {
	ConversationID        int64     `json:"conversation_id"`
	ConversationUpdatedAt time.Time `json:"conversation_updated_at"`
	User                  User      `json:"user"`
	LastMessageID         int64     `json:"last_message_id"`
	LastSenderID          int64     `json:"last_sender_id"`
	LastMessageContent    string    `json:"last_message_content"`
	LastMessageCreatedAt  time.Time `json:"last_message_created_at"`
}

func (q *Queries) ListUserConversations(ctx context.Context, arg ListUserConversationsParams) ([]ListUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, listUserConversations, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserConversationsRow{}
	for rows.Next() {
		var i ListUserConversationsRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.ConversationUpdatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Email,
			&i.User.DisplayName,
			&i.User.Bio,
			&i.User.AvatarUrl,
			&i.User.Role,
			&i.User.Provider,
			&i.User.FollowersCount,
			&i.User.FollowingCount,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.LastMessageID,
			&i.LastSenderID,
			&i.LastMessageContent,
			&i.LastMessageCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations
SET updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) TouchConversation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchConversation, id)
	return err
}
