// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notification.sql

package db

import (
	"context"
	"database/sql"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
  recipient_id, actor_id, tweet_id, type
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, recipient_id, actor_id, tweet_id, type, is_read, created_at
`

type CreateNotificationParams struct {
	RecipientID int64         `json:"recipient_id"`
	ActorID     int64         `json:"actor_id"`
	TweetID     sql.NullInt64 `json:"tweet_id"`
	Type        string        `json:"type"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.RecipientID,
		arg.ActorID,
		arg.TweetID,
		arg.Type,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.ActorID,
		&i.TweetID,
		&i.Type,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*) FROM notifications
WHERE recipient_id = $1 AND is_read = FALSE
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, recipientID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadNotificationCount, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, recipient_id, actor_id, tweet_id, type, is_read, created_at FROM notifications
WHERE recipient_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	RecipientID int64 `json:"recipient_id"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, arg.RecipientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.ActorID,
			&i.TweetID,
			&i.Type,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE recipient_id = $1 AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, recipientID int64) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, recipientID)
	return err
}
