// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRetweet(ctx context.Context, arg CreateRetweetParams) (CreateRetweetRow, error)
	CreateTweet(ctx context.Context, arg CreateTweetParams) (Tweet, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecrementParentReplyCount(ctx context.Context, id int64) error
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteRefreshTokensByUser(ctx context.Context, userID int64) error
	DeleteRetweetByUser(ctx context.Context, arg DeleteRetweetByUserParams) (DeleteRetweetByUserRow, error)
	DeleteTweetByOwner(ctx context.Context, arg DeleteTweetByOwnerParams) (Tweet, error)
	FollowUser(ctx context.Context, arg FollowUserParams) (bool, error)
	GetFollowedUserIDs(ctx context.Context, arg GetFollowedUserIDsParams) ([]int64, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetTopHashtagsAllTime(ctx context.Context, limit int32) ([]Hashtag, error)
	GetTrendingHashtagsLast24h(ctx context.Context, limit int32) ([]Hashtag, error)
	GetTweet(ctx context.Context, arg GetTweetParams) (GetTweetRow, error)
	GetTweetsByIDs(ctx context.Context, arg GetTweetsByIDsParams) ([]GetTweetsByIDsRow, error)
	GetUnreadNotificationCount(ctx context.Context, recipientID int64) (int64, error)
	GetUser(ctx context.Context, arg GetUserParams) (GetUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserRetweet(ctx context.Context, arg GetUserRetweetParams) (Tweet, error)
	GetUsersByIDs(ctx context.Context, arg GetUsersByIDsParams) ([]GetUsersByIDsRow, error)
	IncrementParentReplyCount(ctx context.Context, id int64) error
	IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error)
	IsTweetLiked(ctx context.Context, arg IsTweetLikedParams) (bool, error)
	LikeTweet(ctx context.Context, arg LikeTweetParams) (bool, error)
	LinkTweetHashtag(ctx context.Context, arg LinkTweetHashtagParams) error
	ListFollowersUsers(ctx context.Context, arg ListFollowersUsersParams) ([]ListFollowersUsersRow, error)
	ListFollowingFeed(ctx context.Context, arg ListFollowingFeedParams) ([]ListFollowingFeedRow, error)
	ListFollowingUsers(ctx context.Context, arg ListFollowingUsersParams) ([]ListFollowingUsersRow, error)
	ListForYouFeed(ctx context.Context, arg ListForYouFeedParams) ([]ListForYouFeedRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListSuggestedUsers(ctx context.Context, arg ListSuggestedUsersParams) ([]ListSuggestedUsersRow, error)
	ListTopUsers(ctx context.Context, arg ListTopUsersParams) ([]User, error)
	ListTweetReplies(ctx context.Context, arg ListTweetRepliesParams) ([]ListTweetRepliesRow, error)
	ListUserTweets(ctx context.Context, arg ListUserTweetsParams) ([]ListUserTweetsRow, error)
	MarkAllNotificationsRead(ctx context.Context, recipientID int64) error
	SearchHashtagsByPrefix(ctx context.Context, arg SearchHashtagsByPrefixParams) ([]Hashtag, error)
	SearchTweetsByHashtag(ctx context.Context, arg SearchTweetsByHashtagParams) ([]SearchTweetsByHashtagRow, error)
	SearchTweetsFullText(ctx context.Context, arg SearchTweetsFullTextParams) ([]SearchTweetsFullTextRow, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	UnfollowUser(ctx context.Context, arg UnfollowUserParams) (bool, error)
	UnlikeTweet(ctx context.Context, arg UnlikeTweetParams) (bool, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertHashtag(ctx context.Context, text string) (Hashtag, error)
}

var _ Querier = (*Queries)(nil)
