// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, email, display_name, bio, avatar_url, role, provider
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, username, email, display_name, bio, avatar_url, role, provider, followers_count, following_count, created_at, updated_at
`

type CreateUserParams struct {
	Username    string  `json:"username"`
	Email       string  `json:"email"`
	DisplayName *string `json:"display_name"`
	Bio         *string `json:"bio"`
	AvatarUrl   *string `json:"avatar_url"`
	Role        string  `json:"role"`
	Provider    string  `json:"provider"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
		arg.Role,
		arg.Provider,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Provider,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT u.id, u.username, u.email, u.display_name, u.bio, u.avatar_url, u.role, u.provider, u.followers_count, u.following_count, u.created_at, u.updated_at,
  EXISTS(SELECT 1 FROM follows f WHERE f.following_id = u.id AND f.follower_id = $2) AS is_following
FROM users u
WHERE u.id = $1 LIMIT 1
`

type GetUserParams struct {
	ID       int64  `json:"id"`
	ViewerID *int64 `json:"viewer_id"`
}

type GetUserRow struct {
	User        User `json:"user"`
	IsFollowing bool `json:"is_following"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, arg.ID, arg.ViewerID)
	var i GetUserRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.DisplayName,
		&i.User.Bio,
		&i.User.AvatarUrl,
		&i.User.Role,
		&i.User.Provider,
		&i.User.FollowersCount,
		&i.User.FollowingCount,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.IsFollowing,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, display_name, bio, avatar_url, role, provider, followers_count, following_count, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Provider,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, display_name, bio, avatar_url, role, provider, followers_count, following_count, created_at, updated_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Provider,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT u.id, u.username, u.email, u.display_name, u.bio, u.avatar_url, u.role, u.provider, u.followers_count, u.following_count, u.created_at, u.updated_at,
  EXISTS(SELECT 1 FROM follows f WHERE f.following_id = u.id AND f.follower_id = $1) AS is_following
FROM users u
WHERE u.id = ANY($2::bigint[])
`

type GetUsersByIDsParams struct {
	ViewerID *int64  `json:"viewer_id"`
	UserIds  []int64 `json:"user_ids"`
}

type GetUsersByIDsRow struct {
	User        User `json:"user"`
	IsFollowing bool `json:"is_following"`
}

func (q *Queries) GetUsersByIDs(ctx context.Context, arg GetUsersByIDsParams) ([]GetUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, arg.ViewerID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersByIDsRow{}
	for rows.Next() {
		var i GetUsersByIDsRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Username,
			&i.User.Email,
			&i.User.DisplayName,
			&i.User.Bio,
			&i.User.AvatarUrl,
			&i.User.Role,
			&i.User.Provider,
			&i.User.FollowersCount,
			&i.User.FollowingCount,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.IsFollowing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS(
  SELECT 1 FROM follows WHERE follower_id = $1 AND following_id = $2
)
`

type IsFollowingParams struct {
	FollowerID  int64 `json:"follower_id"`
	FollowingID int64 `json:"following_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FollowingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFollowersUsers = `-- name: ListFollowersUsers :many
SELECT u.id, u.username, u.email, u.display_name, u.bio, u.avatar_url, u.role, u.provider, u.followers_count, u.following_count, u.created_at, u.updated_at,
  EXISTS(SELECT 1 FROM follows f2 WHERE f2.following_id = u.id AND f2.follower_id = $4) AS is_following
FROM users u
JOIN follows f ON u.id = f.follower_id
WHERE f.following_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFollowersUsersParams struct {
	FollowingID int64  `json:"following_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
	ViewerID    *int64 `json:"viewer_id"`
}

type ListFollowersUsersRow struct {
	User        User `json:"user"`
	IsFollowing bool `json:"is_following"`
}

func (q *Queries) ListFollowersUsers(ctx context.Context, arg ListFollowersUsersParams) ([]ListFollowersUsersRow, error) {
	rows, err := q.db.Query(ctx, listFollowersUsers,
		arg.FollowingID,
		arg.Limit,
		arg.Offset,
		arg.ViewerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowersUsersRow{}
	for rows.Next() {
		var i ListFollowersUsersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Username,
			&i.User.Email,
			&i.User.DisplayName,
			&i.User.Bio,
			&i.User.AvatarUrl,
			&i.User.Role,
			&i.User.Provider,
			&i.User.FollowersCount,
			&i.User.FollowingCount,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.IsFollowing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowingUsers = `-- name: ListFollowingUsers :many
SELECT u.id, u.username, u.email, u.display_name, u.bio, u.avatar_url, u.role, u.provider, u.followers_count, u.following_count, u.created_at, u.updated_at,
  EXISTS(SELECT 1 FROM follows f2 WHERE f2.following_id = u.id AND f2.follower_id = $4) AS is_following
FROM users u
JOIN follows f ON u.id = f.following_id
WHERE f.follower_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFollowingUsersParams struct {
	FollowerID int64  `json:"follower_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
	ViewerID   *int64 `json:"viewer_id"`
}

type ListFollowingUsersRow struct {
	User        User `json:"user"`
	IsFollowing bool `json:"is_following"`
}

func (q *Queries) ListFollowingUsers(ctx context.Context, arg ListFollowingUsersParams) ([]ListFollowingUsersRow, error) {
	rows, err := q.db.Query(ctx, listFollowingUsers,
		arg.FollowerID,
		arg.Limit,
		arg.Offset,
		arg.ViewerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingUsersRow{}
	for rows.Next() {
		var i ListFollowingUsersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Username,
			&i.User.Email,
			&i.User.DisplayName,
			&i.User.Bio,
			&i.User.AvatarUrl,
			&i.User.Role,
			&i.User.Provider,
			&i.User.FollowersCount,
			&i.User.FollowingCount,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.IsFollowing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuggestedUsers = `-- name: ListSuggestedUsers :many
SELECT u.id, u.username, u.email, u.display_name, u.bio, u.avatar_url, u.role, u.provider, u.followers_count, u.following_count, u.created_at, u.updated_at,
  EXISTS(SELECT 1 FROM follows f2 WHERE f2.following_id = u.id AND f2.follower_id = $4) AS is_following
FROM users u
LEFT JOIN follows f ON f.following_id = u.id AND f.follower_id = $1
WHERE u.id != $1
ORDER BY (CASE WHEN f.follower_id IS NULL THEN 0 ELSE 1 END) ASC, u.followers_count DESC
LIMIT $2 OFFSET $3
`

type ListSuggestedUsersParams struct {
	FollowerID int64  `json:"follower_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
	ViewerID   *int64 `json:"viewer_id"`
}

type ListSuggestedUsersRow struct {
	User        User `json:"user"`
	IsFollowing bool `json:"is_following"`
}

func (q *Queries) ListSuggestedUsers(ctx context.Context, arg ListSuggestedUsersParams) ([]ListSuggestedUsersRow, error) {
	rows, err := q.db.Query(ctx, listSuggestedUsers,
		arg.FollowerID,
		arg.Limit,
		arg.Offset,
		arg.ViewerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSuggestedUsersRow{}
	for rows.Next() {
		var i ListSuggestedUsersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Username,
			&i.User.Email,
			&i.User.DisplayName,
			&i.User.Bio,
			&i.User.AvatarUrl,
			&i.User.Role,
			&i.User.Provider,
			&i.User.FollowersCount,
			&i.User.FollowingCount,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.IsFollowing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopUsers = `-- name: ListTopUsers :many
SELECT id, username, email, display_name, bio, avatar_url, role, provider, followers_count, following_count, created_at, updated_at FROM users
ORDER BY followers_count DESC
LIMIT $1 OFFSET $2
`

type ListTopUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTopUsers(ctx context.Context, arg ListTopUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listTopUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.Role,
			&i.Provider,
			&i.FollowersCount,
			&i.FollowingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT u.id, u.username, u.email, u.display_name, u.bio, u.avatar_url, u.role, u.provider, u.followers_count, u.following_count, u.created_at, u.updated_at,
  EXISTS(SELECT 1 FROM follows f WHERE f.following_id = u.id AND f.follower_id = $4) AS is_following
FROM users u
WHERE u.username ILIKE '%' || $1 || '%'
   OR u.display_name ILIKE '%' || $1 || '%'
ORDER BY u.followers_count DESC
LIMIT $2 OFFSET $3
`

type SearchUsersParams struct {
	Column1  *string `json:"column_1"`
	Limit    int32   `json:"limit"`
	Offset   int32   `json:"offset"`
	ViewerID *int64  `json:"viewer_id"`
}

type SearchUsersRow struct {
	User        User `json:"user"`
	IsFollowing bool `json:"is_following"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers,
		arg.Column1,
		arg.Limit,
		arg.Offset,
		arg.ViewerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Username,
			&i.User.Email,
			&i.User.DisplayName,
			&i.User.Bio,
			&i.User.AvatarUrl,
			&i.User.Role,
			&i.User.Provider,
			&i.User.FollowersCount,
			&i.User.FollowingCount,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.IsFollowing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
  bio = $2,
  display_name = $3,
  avatar_url = $4,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, username, email, display_name, bio, avatar_url, role, provider, followers_count, following_count, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          int64   `json:"id"`
	Bio         *string `json:"bio"`
	DisplayName *string `json:"display_name"`
	AvatarUrl   *string `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Bio,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Provider,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
